#!/usr/bin/env ruby

print "Checking for config updates ... "
Dir.chdir File.dirname __FILE__ do
  `git fetch 2>/dev/null`
  results  = `git status --porcelain -b`.split "\n"
  status   = results.shift =~ /\[(.*?)\]/ && $1

  ahead   = status =~ /ahead (\d+)/ && $1
  behind  = status =~ /behind (\d+)/ && $1
  changed = !results.count.zero?

  next unless ahead || behind || changed
  if ahead || behind
    puts "\e[033;1m#{status}\e[0m"
  elsif changed
    puts
    system "git s"
  else
    puts "None found"
  end
end

