#!/usr/bin/env ruby

CHECK_FILE = "last_check"
MAX_FREQ   = 24 * 60 * 60

Dir.chdir File.dirname __FILE__ do
  if File.exists? CHECK_FILE
    age   = Time.now - File.mtime(CHECK_FILE)
    force = ARGV.shift
    exit unless force || age > MAX_FREQ
  end

  print "Checking for config updates ... "
  `touch ./last_check && git fetch origin 2>/dev/null`

  results  = `git status --porcelain -b`.split "\n"
  status   = results.shift =~ /\[(.*?)\]/ && $1

  ahead   = status =~ /ahead (\d+)/ && $1
  behind  = status =~ /behind (\d+)/ && $1
  changed = !results.count.zero?

  exit unless ahead || behind || changed
  if ahead || behind
    puts "\e[033;1m#{status}\e[0m"
  elsif changed
    puts
    system "git s"
  else
    puts "None found"
  end
end

