" This is standard pathogen and Vim setup
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'mileszs/ack.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-fugitive'
Bundle 'kchmck/vim-coffee-script'
Bundle 'junegunn/vim-easy-align'
Bundle 'regedarek/ZoomWin'
Bundle 'travitch/hasksyn'

filetype plugin indent on

syntax on

" Highlight hamlc as haml
au BufRead,BufNewFile *.hamlc set ft=haml

" Use 7.4 hybrid numbering
set relativenumber
set number

" Keep temp files in a central location
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,/var/tmp,/tmp

" Use width-2 soft tabs
set expandtab
set shiftwidth=2
set softtabstop=2
set smartindent

" Better search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Shell-style tab completion
set wildmenu
set wildmode=list:longest

" CtrlP .ignore
set wildignore+=*/cabal-dev/*,*/node_modules/*,*.so,*.o,*.hi

" Use 256 color schemes
set t_Co=256
try
  colorscheme tir_black
catch
  colorscheme pablo
endtry

" Allow backspacing over auto-indents
set backspace=indent,eol,start

" Trailing whitespace tools
highlight ExtraWhitespace ctermbg=237 guibg=237
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Save on losing focus
au FocusLost * :wa

" GitGutter
highlight clear SignColumn
let g:gitgutter_sign_column_always = 1

" Open ggrep in a quickfix window
autocmd QuickFixCmdPost *grep* cwindow

" Tweaks
let mapleader=","

map <leader><leader> <c-^>
map <leader>r :so $MYVIMRC<cr>
nnoremap <leader>ev <c-w><c-v><c-l>:e $MYVIMRC<cr>

map <leader>a :Ack 
map <leader>b :NERDTreeToggle<cr>
map <leader>v :ccl<cr>
map <leader>x :noh<cr>

" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign with a Vim movement
nmap <Leader>l <Plug>(EasyAlign)

" Slightly faster paging
nnoremap <c-e> 5<c-e>
nnoremap <c-y> 5<c-y>

" Window navigation
map <Tab>J :split<cr><c-w>j
map <Tab>L :vsplit<cr><c-w>l

nnoremap <Tab>j <c-w>j
nnoremap <Tab>k <c-w>k
nnoremap <Tab>h <c-w>h
nnoremap <Tab>l <c-w>l
inoremap <Tab>j <esc><c-w>j
inoremap <Tab>k <esc><c-w>k
inoremap <Tab>h <esc><c-w>h
inoremap <Tab>l <esc><c-w>l

" Let's do this
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap jj <esc>

" Move line-wise on wrapped lines
nnoremap j gj
nnoremap k gk

" Easier command entry
nnoremap ; :

" Indent
vnoremap < <gv
vnoremap > >gv

" Overtone helpers
" map <leader>x :Eval<cr>
" map <leader>q :Eval (stop)<cr>

" Spec helpers
function! SpecFile()
  !bundle exec rspec %
endfunction
function! SpecFiles()
  !bundle exec rspec
endfunction
nnoremap <leader>s :call SpecFile()<CR>
nnoremap <leader>S :call SpecFiles()<CR>

let @f='/describeN:s/ do/, :focus do:noh'

