" This is standard pathogen and Vim setup
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

" File exploration
Bundle 'mileszs/ack.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'

" Git integration
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-fugitive'

" Coloring and syntax highlighting
Bundle 'altercation/vim-colors-solarized'
Bundle 'travitch/hasksyn'
Bundle 'kchmck/vim-coffee-script'
Bundle 'slim-template/vim-slim'

" Text manipulation
Bundle 'junegunn/vim-easy-align'
Bundle 'scrooloose/nerdcommenter'

" Spec running
Bundle 'skalnik/vim-vroom'
Bundle 'altercation/vim-colors-solarized'

filetype plugin indent on

syntax on

" Highlight hamlc as haml
au BufRead,BufNewFile *.hamlc set ft=haml

" Use 7.4 hybrid numbering
set relativenumber
set number

" Keep temp files in a central location
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,/var/tmp,/tmp

" Use width-2 soft tabs
set expandtab
set shiftwidth=2
set softtabstop=2
set smartindent

" Better search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Shell-style tab completion
set wildmenu
set wildmode=list:longest

" CtrlP .ignore
set wildignore+=*/cabal-dev/*,*/node_modules/*,*.so,*.o,*.hi

" Use 256 color schemes
set t_Co=256
try
  colorscheme tir_black
  " set background=light
  " colorscheme solarized
catch
  colorscheme pablo
endtry

" Allow backspacing over auto-indents
set backspace=indent,eol,start

" Trailing whitespace tools
highlight ExtraWhitespace ctermbg=237 guibg=237
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Save on losing focus
au FocusLost * :wa

" GitGutter
highlight clear SignColumn
let g:gitgutter_sign_column_always = 1

" Open ggrep in a quickfix window
autocmd QuickFixCmdPost *grep* cwindow

" Tweaks
let mapleader=","

map <leader><leader> <c-^>

map <Leader>a :!bundle exec rake && bundle exec rspec<cr>
map <Leader>A :!bundle exec rake clean && bundle exec rake && bundle exec rspec<cr>
map <leader>b :NERDTreeToggle<cr>
map <leader>c :!clear && bundle exec rake<cr>
map <leader>C :!bundle exec rake clean && bundle exec rake<cr>
nnoremap <leader>ev <c-w><c-v><c-l>:e $MYVIMRC<cr>
map <leader>g :Ack
map <leader>r :so $MYVIMRC<cr>
map <Leader>s :VroomRunNearestTest<cr>
map <leader>S :VroomRunTestFile<cr>
map <leader>x :noh \| ccl \| NERDTreeClose \| redraw!<cr>

" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)

" Slightly faster paging
nnoremap <c-e> 5<c-e>
nnoremap <c-y> 5<c-y>

" Window navigation
map <Tab>J :split<cr><c-w>j
map <Tab>L :vsplit<cr><c-w>l

nnoremap <Tab>j <c-w>j
nnoremap <Tab>k <c-w>k
nnoremap <Tab>h <c-w>h
nnoremap <Tab>l <c-w>l
inoremap <Tab>j <esc><c-w>j
inoremap <Tab>k <esc><c-w>k
inoremap <Tab>h <esc><c-w>h
inoremap <Tab>l <esc><c-w>l

" Let's do this
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap jj <esc>

" Move line-wise on wrapped lines
nnoremap j gj
nnoremap k gk

" Indent
vnoremap < <gv
vnoremap > >gv

" Overtone helpers
" map <leader>x :Eval<cr>
" map <leader>q :Eval (stop)<cr>
